# Generated by Django 4.1.3 on 2022-12-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toyota", "0004_order_productinorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="sum",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
